package com.example.ui.localization

data class Strings(
    val appName: String,
    val home: String,
    val servers: String,
    val settings: String,
    val splitTunneling: String,
    val connected: String,
    val connecting: String,
    val disconnected: String,
    val error: String,
    val connect: String,
    val disconnect: String,
    val selectServer: String,
    val selectedServer: String,
    val quickConnect: String,
    val lastUpdated: String,
    val totalServers: String,
    val refreshServers: String,
    val searchPlaceholder: String,
    val filterCountry: String,
    val filterProtocol: String,
    val sortBy: String,
    val ping: String,
    val speed: String,
    val score: String,
    val users: String,
    val allCountries: String,
    val allProtocols: String,
    val tcpOnly: String,
    val udpSupported: String,
    val minSpeedMbps: String,
    val maxPingMs: String,
    val download: String,
    val upload: String,
    val duration: String,
    val serverDetails: String,
    val ipAddress: String,
    val hostname: String,
    val port: String,
    val uptime: String,
    val operator: String,
    val testPing: String,
    val testingPing: String,
    val sourcesTitle: String,
    val sourcesSubtitle: String,
    val protocolTitle: String,
    val authMethodTitle: String,
    val themeTitle: String,
    val languageTitle: String,
    val lightTheme: String,
    val darkTheme: String,
    val systemTheme: String,
    val english: String,
    val persian: String,
    val splitTunnelTitle: String,
    val splitTunnelSubtitle: String,
    val modeExclude: String,
    val modeInclude: String,
    val modeExcludeDesc: String,
    val modeIncludeDesc: String,
    val searchApps: String,
    val selectedAppsCount: String,
    val aboutTitle: String,
    val aboutDesc: String,
    val sourceOfficialApi: String,
    val sourceOfficialWeb: String,
    val sourceMirrorCroatia1: String,
    val sourceMirrorCroatia2: String,
    val sourceMirrorCroatia3: String,
    val sourceMirrorArmenia: String,
    val sourceMirrorCroatia4: String,
    val sourceMirrorCroatia5: String,
    val dnsTitle: String,
    val dnsSubtitle: String,
    val dnsModePreset: String,
    val dnsModeCustom: String,
    val dnsPrimary: String,
    val dnsSecondary: String,
    val dnsCustomPlaceholder: String,
    val logsTitle: String,
    val clearLogs: String,
    val copyLogs: String,
    val logsCopied: String,
    val clearDatabase: String,
    val clearDatabaseSubtitle: String,
    val databaseCleared: String,
    val hostModeTitle: String,
    val hostModeSubtitle: String,
    val hostModeHostname: String,
    val hostModeIp: String,
    val addServer: String,
    val serverNameHint: String,
    val serverHostHint: String,
    val serverPortHint: String,
    val serverUsernameHint: String,
    val serverPasswordHint: String,
    val serverHubHint: String,
    val serverAuthMethodHint: String,
    val serverProtocolHint: String,
    val cancel: String,
    val addAndConnect: String
)

object Localization {
    val en = Strings(
        appName = "VPNGate SoftEther",
        home = "Home",
        servers = "Servers",
        settings = "Settings",
        splitTunneling = "Split Tunneling",
        connected = "Connected",
        connecting = "Connecting...",
        disconnected = "Disconnected",
        error = "Connection Error",
        connect = "CONNECT",
        disconnect = "DISCONNECT",
        selectServer = "Select a Server",
        selectedServer = "Current Server",
        quickConnect = "Quick Connect",
        lastUpdated = "Last Updated",
        totalServers = "Total Servers",
        refreshServers = "Refresh List",
        searchPlaceholder = "Search by country, IP or host...",
        filterCountry = "Country",
        filterProtocol = "Protocol",
        sortBy = "Sort by",
        ping = "Ping",
        speed = "Speed",
        score = "Score",
        users = "Users",
        allCountries = "All Countries",
        allProtocols = "All Protocols",
        tcpOnly = "SoftEther TCP",
        udpSupported = "SoftEther UDP (RUDP)",
        minSpeedMbps = "Min Speed (Mbps)",
        maxPingMs = "Max Ping (ms)",
        download = "Download",
        upload = "Upload",
        duration = "Duration",
        serverDetails = "Server Information",
        ipAddress = "IP Address",
        hostname = "DDNS Hostname",
        port = "SoftEther Port",
        uptime = "Uptime",
        operator = "Operator",
        testPing = "Test Ping",
        testingPing = "Pinging...",
        sourcesTitle = "Server Data Sources",
        sourcesSubtitle = "Enable or disable mirror links & APIs",
        protocolTitle = "SoftEther Protocol Mode",
        authMethodTitle = "Authentication Method",
        themeTitle = "App Theme",
        languageTitle = "Language / زبان",
        lightTheme = "Light Theme",
        darkTheme = "Dark Theme",
        systemTheme = "System Default",
        english = "English",
        persian = "فارسی (Persian)",
        splitTunnelTitle = "Split Tunneling",
        splitTunnelSubtitle = "Select apps to bypass or restrict through VPN",
        modeExclude = "Bypass Selected Apps",
        modeInclude = "Tunnel Only Selected Apps",
        modeExcludeDesc = "Selected applications will bypass the VPN connection.",
        modeIncludeDesc = "Only selected applications will use the VPN connection.",
        searchApps = "Search installed apps...",
        selectedAppsCount = "Selected Apps",
        aboutTitle = "About VPNGate SoftEther",
        aboutDesc = "High-speed VPN client powered by VPNGate servers and SoftEther VPN protocol with UDP V2/V1 acceleration.",
        sourceOfficialApi = "Official VPNGate iPhone CSV API",
        sourceOfficialWeb = "VPNGate Original Website",
        sourceMirrorCroatia1 = "Mirror 1 (Croatia)",
        sourceMirrorCroatia2 = "Mirror 2 (Croatia)",
        sourceMirrorCroatia3 = "Mirror 3 (Croatia)",
        sourceMirrorArmenia = "Mirror 4 (Armenia)",
        sourceMirrorCroatia4 = "Mirror 5 (Croatia)",
        sourceMirrorCroatia5 = "Mirror 6 (Croatia)",
        dnsTitle = "Custom DNS Settings",
        dnsSubtitle = "Select preset DNS or specify custom IP addresses",
        dnsModePreset = "Preset DNS (Shecan, Electro, etc.)",
        dnsModeCustom = "Custom DNS IP Addresses",
        dnsPrimary = "Primary DNS Server",
        dnsSecondary = "Secondary DNS Server",
        dnsCustomPlaceholder = "e.g. 178.22.122.100",
        logsTitle = "SoftEther Log Output",
        clearLogs = "Clear Logs",
        copyLogs = "Copy Logs",
        logsCopied = "Logs copied to clipboard",
        clearDatabase = "Clear Local Database",
        clearDatabaseSubtitle = "Delete all cached servers and reset local storage",
        databaseCleared = "Local database cleared",
        hostModeTitle = "Connection Target Address",
        hostModeSubtitle = "Connect using Hostname or Direct Server IP",
        hostModeHostname = "Hostname (DDNS)",
        hostModeIp = "Direct Server IP",
        addServer = "Add Custom Server",
        serverNameHint = "Server Name (e.g. My Server)",
        serverHostHint = "IP or Hostname",
        serverPortHint = "Port (default 443)",
        serverUsernameHint = "Username (default: vpn)",
        serverPasswordHint = "Password (default: vpn)",
        serverHubHint = "Hub Name (default: VPNGATE)",
        serverAuthMethodHint = "Auth Method",
        serverProtocolHint = "Protocol",
        cancel = "Cancel",
        addAndConnect = "Add & Connect"
    )

    val fa = Strings(
        appName = "وی‌پی‌ان وی‌پی‌ان‌گیت سافت‌اتر",
        home = "خانه",
        servers = "سرورها",
        settings = "تنظیمات",
        splitTunneling = "اسپلیت تونلینگ",
        connected = "متصل شد",
        connecting = "در حال اتصال...",
        disconnected = "قطع شده",
        error = "خطای اتصال",
        connect = "اتصال به وی‌پی‌ان",
        disconnect = "قطع اتصال",
        selectServer = "انتخاب سرور",
        selectedServer = "سرور انتخاب شده",
        quickConnect = "اتصال سریع",
        lastUpdated = "آخرین بروزرسانی",
        totalServers = "تعداد کل سرورها",
        refreshServers = "بروزرسانی لیست",
        searchPlaceholder = "جستجو بر اساس کشور، آدرس آی‌پی یا هاست...",
        filterCountry = "کشور",
        filterProtocol = "پروتکل",
        sortBy = "مرتب‌سازی بر اساس",
        ping = "پینگ (تاخیر)",
        speed = "سرعت",
        score = "امتیاز",
        users = "کاربران",
        allCountries = "همه کشورها",
        allProtocols = "همه پروتکل‌ها",
        tcpOnly = "سافت‌اتر TCP",
        udpSupported = "سافت‌اتر UDP (RUDP)",
        minSpeedMbps = "حداقل سرعت (مگابیت)",
        maxPingMs = "حداکثر پینگ (میلی‌ثانیه)",
        download = "دانلود",
        upload = "آپلود",
        duration = "مدت زمان",
        serverDetails = "اطلاعات کامل سرور",
        ipAddress = "آدرس آی‌پی",
        hostname = "نام هاست دی‌دی‌ان‌اس",
        port = "پورت سافت‌اتر",
        uptime = "زمان فعالیت",
        operator = "اپراتور",
        testPing = "تست پینگ",
        testingPing = "در حال اندازه گیری...",
        sourcesTitle = "منابع و آینه‌های دریافت سرور",
        sourcesSubtitle = "فعال و غیرفعال‌سازی منابع و لینک‌های VPNGate",
        protocolTitle = "حالت پروتکل SoftEther",
        authMethodTitle = "روش احراز هویت",
        themeTitle = "پوسته برنامه",
        languageTitle = "زبان برنامه / Language",
        lightTheme = "تم روشن",
        darkTheme = "تم تیره",
        systemTheme = "پیش‌فرض سیستم",
        english = "English (انگلیسی)",
        persian = "فارسی",
        splitTunnelTitle = "اسپلیت تونلینگ (مدیریت برنامه)",
        splitTunnelSubtitle = "استثنا کردن یا محدودسازی برنامه‌ها برای استفاده از وی‌پی‌ان",
        modeExclude = "استثنا کردن برنامه‌های انتخاب شده",
        modeInclude = "فقط برنامه‌های انتخاب شده",
        modeExcludeDesc = "برنامه‌های انتخاب شده بدون وی‌پی‌ان کار خواهند کرد.",
        modeIncludeDesc = "تنها برنامه‌های انتخاب شده از تونل وی‌پی‌ان عبور می‌کنند.",
        searchApps = "جستجوی برنامه‌های نصب شده...",
        selectedAppsCount = "برنامه‌های انتخاب شده",
        aboutTitle = "درباره برنامه",
        aboutDesc = "اپلیکیشن وی‌پی‌ان واقعی بر پایه پروتکل SoftEther و سرورهای رایگان VPNGate همراه با شتاب‌دهنده UDP و پایگاه داده داخلی.",
        sourceOfficialApi = "ای‌پی‌آی رسمی آیفون VPNGate (CSV)",
        sourceOfficialWeb = "وب‌سایت اصلی VPNGate",
        sourceMirrorCroatia1 = "سرور آینه ۱ (کرواسی)",
        sourceMirrorCroatia2 = "سرور آینه ۲ (کرواسی)",
        sourceMirrorCroatia3 = "سرور آینه ۳ (کرواسی)",
        sourceMirrorArmenia = "سرور آینه ۴ (ارمنستان)",
        sourceMirrorCroatia4 = "سرور آینه ۵ (کرواسی)",
        sourceMirrorCroatia5 = "سرور آینه ۶ (کرواسی)",
        dnsTitle = "تنظیمات دی‌ان‌اس (DNS)",
        dnsSubtitle = "تنظیم دی‌ان‌اس دلخواه یا استفاده از تحریم‌شکن‌های ایرانی",
        dnsModePreset = "سرویس‌های پیشنهادی (شکن، الکترو و...)",
        dnsModeCustom = "آدرس‌های دی‌ان‌اس دلخواه",
        dnsPrimary = "دی‌ان‌اس اصلی (Primary DNS)",
        dnsSecondary = "دی‌ان‌اس دوم (Secondary DNS)",
        dnsCustomPlaceholder = "مثال: 178.22.122.100",
        logsTitle = "پنجره لاگ خروجی سافت‌اتر (SoftEther)",
        clearLogs = "پاکسازی لاگ",
        copyLogs = "کپی لاگ‌ها",
        logsCopied = "لاگ‌ها در حافظه کپی شدند",
        clearDatabase = "پاکسازی دیتابیس داخلی",
        clearDatabaseSubtitle = "حذف تمام سرورهای ذخیره‌شده و بازنشانی دیتابیس",
        databaseCleared = "دیتابیس داخلی با موفقیت پاکسازی شد",
        hostModeTitle = "آدرس مقصد اتصال VPN",
        hostModeSubtitle = "اتصال با استفاده از هاست‌نیم (DDNS) یا آی‌پی مستقیم سرور",
        hostModeHostname = "هاست‌نیم (Hostname)",
        hostModeIp = "آی‌پی مستقیم (Direct IP)",
        addServer = "افزودن سرور دستی",
        serverNameHint = "نام سرور (مثلا سرور من)",
        serverHostHint = "آی‌پی یا هاست‌نام",
        serverPortHint = "پورت (پیش‌فرض ۴۴۳)",
        serverUsernameHint = "نام کاربری (پیش‌فرض: vpn)",
        serverPasswordHint = "رمز عبور (پیش‌فرض: vpn)",
        serverHubHint = "نام هاب (پیش‌فرض: VPNGATE)",
        serverAuthMethodHint = "روش احراز هویت",
        serverProtocolHint = "پروتکل",
        cancel = "لغو",
        addAndConnect = "افزودن و اتصال"
    )

    fun get(lang: String): Strings = if (lang == "fa") fa else en
}
